# -*- coding: utf-8 -*-
"""PS3reglin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caxvEx0mWClbKL3sF114MVV-mjNwp5hu
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

train = pd.read_csv("/content/train_PS3.csv")
test = pd.read_csv("/content/test_PS3.csv")

features = [
    'month', 'year', 'surface_total', 'surface_covered', 'rooms',
    'bedrooms', 'bathrooms', 'num_parqueaderos', 'num_banos',
    'distance_to_nearest_hospital', 'distance_to_nearest_park',
    'distance_to_nearest_transport_station', 'distance_to_financial_center'
]

target = 'price'

X = train[features]
y = train[target]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

X_test = test[features]
X_train = X_train.fillna(X_train.mean())
X_val = X_val.fillna(X_val.mean())
X_test = X_test.fillna(X_test.mean())

model = LinearRegression()
model.fit(X_train, y_train)

y_pred_val = model.predict(X_val)
mse = mean_squared_error(y_val, y_pred_val)
print(f"Mean Squared Error en validación: {mse}")

X_test = test[features].fillna(X_train.mean())
test['price_predicted'] = model.predict(X_test)

submission = test[['property_id', 'price_predicted']]
submission.rename(columns={'price_predicted': 'price'}, inplace=True)
submission.to_csv("submission.csv", index=False)
print("Archivo 'submission.csv' generado con éxito.")